/*
 * ----- NOTE -----
 * file `app/assets/javascripts/wallaby/core.js` will be automatically generated by
 * `yarn build:js` to bundle all the imports from `app/javascript/wallaby/core.js`
 * Please DO NOT try to modify this generated file.
 * ----------------
 */

import './globals';
import 'jquery-ujs';
import 'moment-timezone';
import 'popper.js';
import 'bootstrap';
import 'tempusdominus-bootstrap-4';
import 'summernote/dist/summernote-bs4';
import 'codemirror/addon/mode/overlay';
import 'codemirror/mode/ruby/ruby';
import 'codemirror/mode/javascript/javascript';
import 'codemirror/mode/markdown/markdown';
import 'codemirror/mode/gfm/gfm';
import 'codemirror/mode/xml/xml';
import 'typeahead.js/dist/typeahead.bundle';
import 'jquery-minicolors';
