x-common-env: &common-env
  RAILS_ENV: development
  # Postgres
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: wallaby_rails_dummy_development
  # MySQL
  MYSQL_HOST: mysql
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: wallaby_rails_dummy_development

services:
  # Ruby on Rails Web App
  web:
    build: .
    container_name: rails_app
    command:
      - /bin/bash
      - -c
      - |
        bundle && bundle exec rails db:setup && rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'
    depends_on:
      - postgres
      - mysql
    environment:
      <<: *common-env
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp

  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      <<: *common-env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      <<: *common-env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mysql_data:
