x-common-env: &common-env
  HISTFILE: ".bash_history"
  # Postgres
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: wallaby_rails_dummy_development
  # MySQL
  MYSQL_HOST: mysql
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: wallaby_rails_dummy_development

services:
  # Ruby on Rails Web App
  web:
    build: .
    container_name: rails_app
    command:
      - /bin/bash
      - -c
      - |
        if [ ! -f ./tmp/db-setup ]; then
          bundle exec rails db:create db:setup
          touch ./tmp/db-setup
        fi

        bundle && \
        rm -f tmp/pids/server.pid && \
        bundle exec rails s -b '0.0.0.0'
    depends_on:
      - postgres
      - mysql
    environment:
      <<: *common-env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ~/.bash_history:/root/.bash_history

  # PostgreSQL Service
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      <<: *common-env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      <<: *common-env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mysql_data:
