require 'adaptors/wallaby/her'
require 'adaptors/wallaby/her/model_decorator'
require 'adaptors/wallaby/her/model_finder'
require 'adaptors/wallaby/her/model_pagination_provider'
require 'adaptors/wallaby/her/model_service_provider'
